[build]
  publish = "."

[[redirects]]
  from = "/candles"
  to = "/activities#candle-making"
  status = 301

[[redirects]]
  from = "/events"
  to = "/activities#events"
  status = 301

[[redirects]]
  from = "/gallery"
  to = "/activities#gallery"
  status = 301
